version: '3'

services:
  app:
    build:
      context: .
      target: ${STAGE}
      dockerfile: Dockerfile

    container_name: factu-qa-app
    image: ${ECR_REGISTRY}/factu-api:qa-${IMAGE_TAG}
    ports:
      - ${APP_PORT}:${APP_PORT}

    # env_file:
    #   - ./.env
