version: '3'

services:
  db:
    image: mysql:8.0
    restart: always
    container_name: dev-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - "3310:3306"
    volumes:
      - ./data-dev:/var/lib/mysql