on:
  push:
    branches:
      - ci-gh

jobs:
  ci: 
    name: ci
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Building image and pushing to DockerHub
      env: 
        DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        IMAGE_TAG: ${{ github.sha }}
        
      run: |
        docker compose -f docker-compose.prod.yml build 
        docker push $DOCKERHUB_USERNAME/jimloza/factuapp-qa:$IMAGE_TAG