on:
  push:
    branches:
      - ci-gh

jobs:

  deploying: 
    needs: build
    name: Deploying to EC2
    runs-on: self-hosted

    steps:
    - name: Login to dockerhub
      run: |
        echo "Corriendo"
