on:
  push:
    branches:
      - ci-gh

jobs:
  ci: 
    name: ci
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Building image and pushing to DockerHub
      env: 
        DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        IMAGE_TAG: ${{ github.sha }}
        
      run: |
        docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
        STAGE="prod" IMAGE_TAG="qa-$IMAGE_TAG" APP_PORT=3000 docker compose -f docker-compose.prod.yml build 
        docker push $DOCKERHUB_USERNAME/factuapp-qa:qa-$IMAGE_TAG

  deploying: 
    needs: ci
    name: Deploying to EC2
    runs-on: self-hosted

    steps:
    - name: deploying
      env:
        IMAGE_TAG: ${{ github.sha }}
        DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: |
        cd ~/Docker-qa
        docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
        sudo IMAGE_TAG="qa-$IMAGE_TAG" docker compose -f docker-compose.prod.yml up -d